# This is a basic workflow to help you get started with Actions

name: Email Notification For PcdcPrivacyNotice.md

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'PcdcPrivacyNotice.md'
  pull_request:
    paths:
      - 'PcdcPrivacyNotice.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Send Email Action
        uses: cinotify/github-action@v1.1.0
        with:
          to: wdandersen@wisc.edu
          subject: 'Document Commit'
          body: 'Document(s) in ${{github.repository}} called PcdcPrivacyNotice was comitted'
     # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
   
      - uses: actions/checkout@v3

      - name: Send Email Action 2
        uses: cinotify/github-action@v1.1.0
        with:
          to: ${{ secrets.EmailList }}
          subject: 'Document Commit'
          body: 'Document(s) in ${{github.repository}} called PcdcPrivacyNotice was comitted'

   # This workflow contains a single job called "build"
