# This is a basic workflow to help you get started with Actions

name: Email Notification For Specific Files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'PcdcPrivacyNotice.md'
      - 'AcceptableUsePolicy.md'
      - 'DataPortalUserGuide.md'
      - 'StatisticalManual.md'
      - 'TermsAndConditions.md'
      - 'index.md'
  pull_request:
    paths:
      - 'PcdcPrivacyNotice.md'
      - 'AcceptableUsePolicy.md'
      - 'DataPortalUserGuide.md'
      - 'StatisticalManual.md'
      - 'TermsAndConditions.md'
      - 'index.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # extract branch name on pull request
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"


  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Send Email Action
        uses: cinotify/github-action@v1.1.0
        with:
          to: 'wandersen01@gmail.com'
          subject: 'Document Commit'
          body: 'A document in ${{github.repository}} called $BRANCH_NAME  was comitted'
  

