name: Email Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'PcdcPrivacyNotice.md'
  pull_request:
    paths:
      - 'PcdcPrivacyNotice.md'

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-secret:
      runs-on: ubuntu-latest
      outputs:
        my-key: ${{ steps.my-key.outputs.defined }}
      steps:
          - id: my-key
            if: "${{ env.MY_KEY != '' }}"
            run: echo "::set-output name=defined::true"
            env:
                MY_KEY: ${{ secrets.EMAILLIST }}
  job1:
      runs-on: ubuntu-latest
      needs: [check-secret]
      if: needs.check-secret.outputs.my-key == 'true'
      steps:
        - uses: actions/checkout@v3
        - name: Send Email Action
          uses: cinotify/github-action@v1.1.0
          with:
            to: ${{ secrets.EMAILLIST }}
            subject: 'Document Commit'
            body: 'Document(s) in ${{github.repository}} called test was comitted'

  job2:
      runs-on: ubuntu-latest
      needs: [check-secret]
      if: needs.check-secret.outputs.my-key != 'true'
      steps:
        - uses: actions/checkout@v3
        - name: Send Email Action
          uses: cinotify/github-action@v1.1.0
          with:
            to: 'wandersen01@gmail.com'
            subject: 'Document Commit'
            body: 'Document(s) in ${{github.repository}} called test was comitted'
    
